version: '2'
services:
  nginx:
    build: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      - backend
    volumes:
      - ./OpenHouse/static:/oh/static:ro
      - ./OpenHouse/media:/oh/media:ro
      - /var/log/nginx:/var/log/nginx
      - ./nginx/html:/etc/nginx/html
      - ./nginx/key:/etc/ssl
    depends_on:
      - oh
  oh:
    container_name: oh
    restart: always
    build :
      context: ./OpenHouse
      dockerfile: Dockerfile.prod
    volumes:
      - /var/run/mysqld:/var/run/mysqld
      - ./OpenHouse:/oh:rw
    networks:
      - backend
    environment:
      - MYSQL_HOST=/var/run/mysqld/mysqld.sock
      - MYSQL_PASSWORD=<MYSQL_PASSWORD>


networks:
  backend: