# syntax=docker/dockerfile:1
FROM python:3.8.13
WORKDIR /
COPY setup.sh create_file.sh requirements.txt ./
RUN sh setup.sh && sh create_file.sh
COPY ./base.html /usr/local/lib/python3.8/site-packages/jet/templates/admin/base.html
WORKDIR /oh
CMD ["sh", "migrate_start.sh"]
EXPOSE 8000