# syntax=docker/dockerfile:1
FROM python:3.8.13
WORKDIR /
COPY setup.sh requirements.txt ./
RUN sh setup.sh
COPY ./base.html /usr/local/lib/python3.8/site-packages/jet/templates/admin/base.html
WORKDIR /oh
CMD  gunicorn --workers=8 --bind :8000 OpenHouse.wsgi
EXPOSE 8000