CREATE DATABASE oh_core
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2018
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2017
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2016
CHARACTER SET utf8
COLLATE utf8_general_ci;
