CREATE DATABASE oh_core
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2018
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2017
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2016
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE DATABASE oh_2019
CHARACTER SET utf8mb4
COLLATE utf8mb4_bin;

CREATE DATABASE oh_2020
CHARACTER SET utf8mb4
COLLATE utf8mb4_bin;

CREATE DATABASE oh_2021
CHARACTER SET utf8mb4
COLLATE utf8mb4_bin;



